version: '3'
services:
  apis:
    image: lagobetech/lgbsc-backend:1.0.10
    container_name: lgbsc-backend
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
      restart_policy:
        max_attempts: 3
    environment:
      NODE_ENV: develop
    networks:
      lagobesc:
        aliases:
          - apis
  www:
    image: lagobetech/lgbsc-frontend:1.0.30
    container_name: lgbsc-frontend
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - apis
    depends_on:
      - apis
    deploy:
      resources:
        limits:
          memory: 128M
      restart_policy:
        max_attempts: 3
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp/letsencrypt:/tmp/letsencrypt
      - /opt/docker/nginx/conf:/etc/nginx/conf.d
    networks:
      lagobesc:
        aliases:
          - www
  letsencrypt:
    image: gordonchan/auto-letsencrypt
    container_name: lgbsc-letsencrypt
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
      restart_policy:
        max_attempts: 3
    environment:
      DOMAINS: sc.lagobe.com adm.sc.lagobe.com
      EMAIL: hello@lagobe.com
      WEBROOT_PATH: /tmp/letsencrypt
      SERVER_CONTAINER: lgbsc-frontend
    links:
      - www
    depends_on:
      - www
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /tmp/letsencrypt:/tmp/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      lagobesc:
        aliases:
          - letsencrypt
  mylineme-blog:
    image: wordpress
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
      restart_policy:
        max_attempts: 3
    environment:
      WORDPRESS_DB_HOST: lagobe-db.c9xkyd68xrpr.ap-southeast-1.rds.amazonaws.com
      WORDPRESS_DB_USER: lagobe
      WORDPRESS_DB_PASSWORD: lagobe_db
      WORDPRESS_DB_NAME: mylineme_blog
    volumes:
      - /tmp/wordpress/wp-content:/var/www/html/wp-content
    networks:
      lagobesc:
        aliases:
          - mylinemeblog
networks:
  lagobesc:
